# This is a basic workflow that is manually triggered

name: Publish Docker images

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Call task on tool-ci Jenkins
      run: echo "Hello ${{ github.event.inputs.name }}"
